### ISSUE TITLE
support for newer NIDAQmx version 17.5.0

### ISSUE THREAD

**Issue by circuit4u** [JaneliaSciComp/NIDAQ.jl#13]
any plan to update to the current NIDAQmx version 17.5.0 (or the latest)

**Comment by bjarthur** [comment]
will do that when i refactor for julia 7.0.  in a month or so hopefully.  busy with gadfly.jl now.  would happily review a PR if you had time.

**Comment by Cody-G** [comment]
Just wanted to say that I'm also hoping to get this package running in julia 0.7 very soon.  Do you have any preference on how it's done? I can probably work on it in the coming week.

**Comment by bjarthur** [comment]
[working on it](https://github.com/JaneliaSciComp/NIDAQ.jl/pull/14)

**Comment by Cody-G** [comment]
Awesome, thank you!  I should be able to test this on hardware this week.

**Comment by bjarthur** [comment]
i still have to run the C header file through Clang.  give me a couple days.

**Comment by Cody-G** [comment]
Got it, I'll keep an eye on the PR and test when ready.

**Comment by bjarthur** [comment]
closed by https://github.com/JaneliaSciComp/NIDAQ.jl/pull/15
