### ISSUE TITLE
cannot add aichannels past ai7

### ISSUE THREAD

**Issue by alexporter8013** [JaneliaSciComp/NIDAQ.jl#17]
When trying to add channels past ai7, i get this error:
```
julia> t = analog_input("Dev1/ai10")
ERROR: NIDAQmx: Requested value is not a supported value for this property. The property value may be invalid because it conflicts with another property.
```
I believe this is caused by:
```
Ref(codeunits(channel),1)
```
I have tested changing this to simply pointer(channel) and pointer(""). Will do a pull request once I'm finished breaking, then fixing.

**Comment by bjarthur** [comment]
closed by https://github.com/JaneliaSciComp/NIDAQ.jl/commit/190fb1d3b692e2663add93f57eae12431eae3d74
