### ISSUE TITLE
Sync modules

### ISSUE THREAD

**Issue by RubensRossi** [JaneliaSciComp/NIDAQ.jl#33]
Hi everyone,

currently I use LabVIEW to acquire the data from a cDAQ 9185 or 9189 and send it then to Julia for calculations.
I managed to read the cDAQ directly with this nice package, however there is one DAQmx function that gives me troubles.

I need to sync the acquisition with all the modules present in the cDAQ (1x NI9215 and 3x NI9229) and so far as I understood, I have to use the DAQmxGetSampClkTimebaseSrc -> DAQmxSetSampClkTimebaseSrc and DAQmxGetSampClkTimebaseRate -> DAQmxSetSampClkTimebaseRate.

Under LabVIEW everything works, but the code is hidden and I cannot find out which functions exactly are used or how they are called.

When I use Julia (Windows, Julia 1.6.1),  I get always a -200077 error (Requested value is not a supported value for this property.).

This is what I tried:
````
task1 = analog_input(dev_name*"Mod4"*"/ai0", range = [-20,20]) # works
task2 = analog_input(dev_name*"Mod3"*"/ai0", range = [-20,20]) # works

# set the fs and continuous sampling
mod_fs = 1e5
NIDAQ.CfgSampClkTiming(task1.th,convert(Ref{UInt8},b""),mod_fs,NIDAQ.Val_Rising,NIDAQ.Val_ContSamps,mod_fs*2) # works
NIDAQ.CfgSampClkTiming(task2.th,convert(Ref{UInt8},b""),mod_fs,NIDAQ.Val_Rising,NIDAQ.Val_ContSamps,mod_fs*2) # works

data = 0.
NIDAQ.DAQmxGetSampClkTimebaseRate(task1.th,Ref(data)) # -> error -200077
data_rate = Ref{Float64}(0)
NIDAQ.DAQmxGetSampClkTimebaseRate(task1.th,data_rate) # -> error -200077
data_div = convert(Ref{UInt32},C_NULL)
NIDAQ.DAQmxGetSampClkTimebaseDiv(task1.th,data_div) # -> error -200077
````

Any idea would be welcome,

Thanks in advance
Rubens

**Comment by RubensRossi** [comment]
Sorry, I forgot to mention that I have the NI DAQmx 20.1 driver and that ``` NIDAQ._getproperties((task.th,),"Samp",true) ``` also gives error for the above functions.

**Comment by bjarthur** [comment]
sorry, not sure i can help.  i'd suggest posting to a labview forum.  more experts there presumably, and your problem is probably not julia specific.

**Comment by bjarthur** [comment]
please do let us know though if/when you fix it.

**Comment by RubensRossi** [comment]
[Here the post on NI forum](https://forums.ni.com/t5/Multifunction-DAQ/DAQmx-Sync-Analog-inputs/m-p/4180785?profile.language=en#M102116)
