### ISSUE TITLE
NIDAQmx version 16.1.0 is not supported

### ISSUE THREAD

**Issue by menyoung** [JaneliaSciComp/NIDAQ.jl#5]
```
julia> using NIDAQ
INFO: Precompiling module NIDAQ.
ERROR: LoadError: NIDAQmx version 16.1.0 is not supported.
```

Also there was a recent bugfix that advanced version 16.0.0 to 16.0.1.

**Comment by menyoung** [comment]
I think even better than an update to add support for newer versions of NI-DAQmx would be a documentation update to give a slightly more detailed explanation of exactly how NI's header file (starting with where to find it?) is converted to create the constants and functions.

**Comment by bjarthur** [comment]
i generally don't have time to add support for every minor release.  is it possible for you to install drivers that are supported?  otherwise, i'm happy to merge a PR that adds support for a new version and/or better docs describing how to do so.

**Comment by menyoung** [comment]
Thanks. I already rolled back to the driver that is supported, which is actually fine for my active machine. I will learn to use Clang.jl and follow the steps to add support for the newest version and submit a PR. Your documentation at the end of the README makes sense to me at first read.

**Comment by bjarthur** [comment]
i am planning to update NIDAQ.jl to julia 0.6 soon after it is released.  i can take care of adding support to the latest NIDAQmx driver at that time if you're willing to wait.
