### ISSUE TITLE
Test errors due to unsupported features of USB 6002 device

### ISSUE THREAD

**Issue by Cody-G** [JaneliaSciComp/NIDAQ.jl#7]
I just discovered that digital input, output, and counter tests fail for my USB 6002 device.  The digital io failures seem to happen because this device doesn't support buffered digital io.  The counter test fails because the device doesn't have any counter channels, and the check for that in the tests doesn't quite work as intended.  I have fixes that I can submit as a PR after #6 merges.

**Comment by bjarthur** [comment]
i'd be happy to review a PR that fixes this.

**Comment by Cody-G** [comment]
Great, I just opened #8

**Comment by bjarthur** [comment]
fixed by #8
